#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc config merge_overlapping_monitors    true
bspc monitor eDP -d     
INTERNAL_OUTPUT="eDP1"
EXTERNAL_OUTPUT="HDMI-A-0"

xrandr | grep $EXTERNAL_OUTPUT | grep " connected "
if [ $? -eq 0 ]; then
    xrandr --output eDP --mode 1920x1080 --output HDMI-A-0 --mode 1440x900 --scale-from 1920x1080 --same-as eDP
    bspc monitor $INTERNAL_OUTPUT -d     
    bspc monitor $INTERNAL_OUTPUT -d     
else
    xrandr --output $INTERNAL_OUTPUT --auto --output $EXTERNAL_OUTPUT --off
    bspc monitor $INTERNAL_OUTPUT -d     
fi
killall nm-applet
killall polybar
killall blueman
killall feh
killall picom
$HOME/.config/polybar/launch.sh &
$HOME/.config/fehinit.sh &
$HOME/dotfiles/micmutelightoff &	
picom --config $HOME/.config/picom/picom.conf &
nm-applet &
blueman-applet & 
greenclip daemon &
dunst -config $HOME/.config/dunst/dunstrc &
bspc config top_padding        37
bspc config bottom_padding     5
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width         1
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc config normal_border_color "#707880"
bspc config focused_border_color "#dadada"
bspc config urgent_border_color "#A54242"
bspc config presel_border_color "#bb141b1e"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr


