#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d     

$HOME/.config/polybar/launch.sh 
$HOME/.config/fehinit.sh &
$HOME/.config/micmutelightoff &	
killall picom 
picom --config $HOME/.config/picom/picom.conf &
killall nm-applet
nm-applet &
blueman-applet & 

bspc config top_padding        28
bspc config bottom_padding     0
bspc config left_padding       0
bspc config right_padding      0
bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc config normal_border_color "#707880"
bspc config focused_border_color "#dadada"
bspc config urgent_border_color "#A54242"
bspc config presel_border_color "#bb141b1e"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true


