#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &
bspc config merge_overlapping_monitors    true
bspc monitor eDP -d 1 2 3 4 
killall nm-applet
killall polybar
killall blueman
killall feh
killall picom
$HOME/.config/polybar/launch.sh &
$HOME/.config/fehinit.sh &	
picom --config $HOME/.config/picom/picom.conf &
nm-applet &
blueman-applet & 
greenclip daemon &
dunst -config $HOME/.config/dunst/dunstrc &
sudo echo 0 | sudo tee /sys/class/leds/platform\:\:micmute/brightness
bspc config top_padding        15
bspc config bottom_padding     48
bspc config left_padding       15
bspc config right_padding      15
bspc config border_width       0
bspc config window_gap         15

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config remove_disabled_monitors true
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action3 resize_corner


bspc config normal_border_color "#707880"
bspc config focused_border_color "#dadada"
bspc config urgent_border_color "#A54242"
bspc config presel_border_color "#bb141b1e"

bspc rule -a Gimp desktop='^8' state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off

bspc config focus_follows_pointer true
xsetroot -cursor_name left_ptr
xinput set-prop 'SynPS/2 Synaptics TouchPad' 304 1 
xinput set-prop 'SynPS/2 Synaptics TouchPad' 303 1 
export _JAVA_AWT_WM_NONREPARENTING=1
XDG_DOWNLOAD_DIR="$HOME/Descargas"
